export const STORAGE_KEYS = {
  COMMENTS: "blog_comments",
  USERS: "blog_users",
  AUTH_TOKEN: "auth_token",
  CURRENT_USER: "blog_current_user",
  THEME: "blog_theme",
  ARTICLE_VIEWS: "blog_article_views",
  ARTICLE_LIKES: "blog_article_likes",
  LIKED_ARTICLES: "blog_liked_articles",
  BOOKMARKS: "blog_bookmarks",
  CONTACT_MESSAGES: "blog_contact_messages",
  CACHED_ARTICLES: 'blog_cached_articles',
  CACHED_CATEGORIES: 'blog_cached_categories',
  CACHED_ADMIN_STATS: 'blog_cached_admin_stats',
  CACHED_ADMIN_COMMENTS: 'blog_cached_admin_comments',
  CACHED_ADMIN_ARTICLE_STATS: 'blog_cached_admin_article_stats',
};
